#!/bin/sh
#
# Note: avr include files are somewhat strangely located
splint  +showfunc -showcolumn \
        -I /usr/lib/avr/include \
        -I letterbox \
        -I letterbox/commons \
        -I letterbox/assert \
        -I letterbox/buttons \
        -I letterbox/lcd \
        -I letterbox/message \
        -I letterbox/uart \
        -I letterbox/timer $@

