#!/bin/sh
gcc -g ../../letterbox/message/message.c ../../commons/commons.c test_message.c mock_eeprom.c assert.c -I . -I ../../commons -I ../../letterbox/message -I ../../letterbox/eeprom && ./a.out

